config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :users, only: [:new, :create, :edit, :show, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :user
  belongs_to :post
  # has_many :votes, as: :voteable
  # has_many :users, through: :posts
  validates :body, presence: true, length: {minimum: 5}

  # extend FriendlyId
  # friendly_id :id, use: :slugged
  # 原本是input.to_s.parameterize，但是parameterize只支援英文跟數字，所以改用babosa的to_slug
  # def normalize_friendly_id(input)
  #   input.to_s.to_slug.normalize.to_s
  # end
  # def should_generate_new_friendly_id?
  #   slug.blank? || id_changed? # slug 為 nil 或 name column 變更時更新
  # end
  def slug_candidates
    [ :id, [:id, :body]]
  end

  # def vote_total
  #   vote_up - vote_down
  # end
  # def vote_up
  #   self.votes.where(vote: true).size
  # end
  # def vote_down
  #   self.votes.where(vote: false).size
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:vote]
  before_action :require_user?, only: [:new, :create]

  def new
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post

    if @comment.save
      flash[:notice] = "Comment has been created!"
      redirect_to post_path(@post)
    else
      render :new
    end

  end
  def vote
    @vote = Vote.create(voteable: @comment, user_id: current_user.id, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "Your vote was not counted."
        end
        redirect_to :back
      end
      format.js
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_comment_path(ct.post, ct, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
     <br/>
    <span id="post_<%= ct.id %>_comment_votes"><%= ct.vote_total %> votes</span>
    <br/>
    <%= link_to vote_post_comment_path(ct.post, ct, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>
  <div class="span6 well">
    <%= ct.body %> </br>
    <% if show_post %>
      on: <%= link_to ct.post.title, post_path(ct.post) %> </br>
    <% end %>
    Created by: <%= ct.user.username %>.
    Created at: <%= ct.created_at %>.
  </div>
</div>

app/views/comments/_form.html.erb
<div class='well'>
  <%= form_for [post, comment] do |f| %>
    <%= f.label :body, "回覆：" %>
    <%= f.text_area :body, rows: 5 %><br />

    <%= f.submit(comment.new_record? ? 'Create Comment.' : 'Edit Comment.', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/comments/new.html.erb
<% if logged_in? %>
  <%= render 'shared/content_title', title: "New Comment!" %>
<% end %>

<%= render 'shared/error', errors: @comment.errors %>

<%= render 'form', post: @post, comment: @comment %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @comment.id %>_comment_votes").html("<%= @comment.vote_total %> votes")
<% else %>
  alert("You can only vote on a comment once.")
<% end %>