config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :users, only: [:new, :create, :edit, :show, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :user, foreign_key: :user_id
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}

  # extend FriendlyId
  # friendly_id :id, use: :slugged
  # # 原本是input.to_s.parameterize，但是parameterize只支援英文跟數字，所以改用babosa的to_slug
  # def normalize_friendly_id(input)
  #   input.to_s.to_slug.normalize.to_s
  # end
  # def should_generate_new_friendly_id?
  #   slug.blank? || id_changed? # slug 為 nil 或 name column 變更時更新
  # end
  def slug_candidates
    [ :id, [:id, :title]]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy, :edit, :vote]
  before_action :require_user?, except: [:index, :show]
  # before_action :require_same_user, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.vote_total}.reverse
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    #@post.user = User.first

    if @post.save
      flash[:notice] = "Your post has been created!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end
  def update
    if @post.update(post_params)
      flash[:notice] = "The post has been updated."
      redirect_to post_path(@post)
    else
      render :edit
    end

  end

  def destroy
  end

  def vote
    @vote = Vote.create(voteable: @post, user_id: current_user.id, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "Your vote was not counted."
        end
        redirect_to :back
      end
      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [] )
  end
  def set_post
    @post = Post.find(params[:id])
  end

end

app/views/posts/_form.html.erb
<div class='well'>
  <%= form_for post do |f| %>
    <%= f.label :title, "主旨："%>
    <%= f.text_field :title %><br />

    <%= f.label :url, "網址：" %>
    <%= f.text_field :url %><br />

    <%= f.label :description, "說明：" %>
    <%= f.text_field :description %><br />

    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text } %>
      <% end %>
    </div>

    <%= f.submit(post.new_record? ? 'Create Post.' : 'Edit Post.', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id="post_<%= post.id %>_votes"><%= post.vote_total %> votes</span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>
  <div class="span8 well">
    <p><%= render post.categories %></p>
    <span class="lead"> <%= link_to post.title, post_path(post) %> </span></br>
    <%= post.description %> </br>
    Learn more >> <%= link_to fix_url(post.url), fix_url(post.url) %> </br>
    Created by: <%= post.user.username %>.
    There are <%= post.comments.size %> comments! </br>
    Created at: <%= display_datetime(post.created_at) %>.
  </div>
</div>

app/views/posts/edit.html.erb
<% if logged_in? %>
  <%= render 'shared/content_title', title: "Edit post!" %>
<% end %>

<%= render 'shared/error', errors: @post.errors %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All Posts!" %>

<%= render @posts %>

app/views/posts/new.html.erb
<% if logged_in? %>
  <%= render 'shared/content_title', title: "New post!" %>
<% end %>

<%= render 'shared/error', errors: @post.errors %>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to "Edit the post.", edit_post_path(@post) %>]
  </p>
<% end %>

<%= render "shared/content_title", title: @post.title %>

<% if logged_in? %>
  <%= render 'comments/form', post: @post, comment: @comment %>
  <hr>
<% end %>

<p>
  <%= render @post %>
</p>

<p>
  <span class="lead">Comments:</span>
  <hr>
  <% @comments.each do |ct| %>
    <%= render "comments/comment", ct: ct %>
  <% end %>
</p>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.id %>_votes").html("<%= @post.vote_total %> votes")
<% else %>
  alert("You can only vote on a post once.")
<% end %>