config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :users, only: [:new, :create, :edit, :show, :update]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li>
  <li>
    <div class='btn-group nav-item'>
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        Categories <span class='caret'></span>
      <% end %>
      <ul class='dropdown-menu'>
        <% Category.all.each do |category| %>
          <li><%= link_to category.name, category_path(category) %> </li>
        <% end %>
        <% if logged_in? and current_user.admin? %>
          <li class='divider'></li>
          <li>
            <%= link_to(new_category_path) do %>
              <i class='icon-plus'></i>
              New Category
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </li>
  <% if logged_in? %>
    <li>
      <div class='nav_item'>
        <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
      </div>
    </li>
    <li>
      <%=link_to "Hi! #{current_user.username}", root_path %>
    </li>
    <li>
      <%= link_to 'Logout', logout_path %>
    </li>

    <li>
      <div class='btn-group nav-item'>
        <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
          <%= "Hi! #{current_user.username}" %><span class='caret'></span>
        <% end %>
        <ul class='dropdown-menu'>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <i class='icon-edit'></i> Edit profile
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class='icon-user'></i> View profile
            <% end %>
          </li>
          <li>
            <%= link_to logout_path do %>
              <i class='icon-arrow-left'></i> Logout
            <% end %>
          </li>
        </ul>
      </div>
    </li>

  <% else %>
    <li>
      <%= link_to 'Login', login_path %>
    </li>
    <li>
      <%= link_to 'Register', register_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>